apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
      - name: productservice
        image: dhanashreegade/productservice:latest    # this is (commented, right side) old before CICD, manual deployment dhanashreegade/productservice:v1 ## Kubernetes may NOT pull new image automatically.
        imagePullPolicy: Always ## Use this line to force Kubernetes to use the local image. Remove it when you push the image to a registry.
        ports:
        - containerPort: 8080

        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: product-config
              key: ASPNETCORE_ENVIRONMENT

        - name: ConnectionStrings__ProductDatabase
          valueFrom:
            secretKeyRef:
              name: product-db-secret
              key: ConnectionStrings__ProductDatabase

        #initContainers:
        #- name: wait-for-postgres
    #image: busybox
  #command: ['sh', '-c', 'until nc -z postgres-service 5433; do echo waiting for db; sleep 2; done;']