apiVersion: v1
kind: Secret
metadata:
  name: product-db-secret
type: Opaque
stringData:
  ConnectionStrings__ProductDatabase: "Host=postgres-service;Port=5432;Database=product_qa_db;Username=postgres;Password=1234"